feat: add support for wait command
GoogleCloudPlatform/cloud-sql-proxy pull request #2041
Opened 2023-11-21 18:32 UTC by enocom

To help ensure the Proxy is up and ready, this commit adds a wait command with an optional `--max` flag to set the maximum time to wait.

By default when invoking this command:

./cloud-sql-proxy wait

The Proxy will wait up to the maximum time for the /startup endpoint to respond. This command requires that the Proxy be started in another process with the HTTP health check enabled. If an alternate health check port or address is used, as in:

./cloud-sql-proxy <INSTANCE_CONNECTION_NAME> --http-address 0.0.0.0 \
  --http-port 9191

Then the wait command must also be told to use the same custom values:

./cloud-sql-proxy wait --http-address 0.0.0.0 \
  --http-port 9191

By default the wait command will wait 30 seconds. To alter this value, use:

./cloud-sql-proxy wait --max 10s

Fixes #1117

2023-11-22 15:53 UTC, jackwotherspoon requested changes

2023-11-22 15:53 UTC, jackwotherspoon commented on cmd/root.go
> +    To help ensure the Proxy is up and ready, the Proxy includes adds a wait
```suggestion
    To help ensure the Proxy is up and ready, the Proxy includes a wait
```

2023-11-22 15:53 UTC, jackwotherspoon commented on cmd/root.go
> +    By default when invoking this command:
This line is slightly confusing ... reads a little funny

2023-11-22 17:28 UTC, jackwotherspoon approved these changes
LGTM

2023-11-27 18:57 UTC, hessjcg approved these changes
LGTM

2023-11-27 18:59 UTC, merged

2024-05-29 01:29 UTC, vvxxvvxx commented
Hi @enocom , is this feature also added in cloud-sql-proxy v1?

2024-05-29 13:25 UTC, jackwotherspoon commented
> Hi @enocom , is this feature also added in cloud-sql-proxy v1?

@vvxxvvxx The wait command is not supported in the v1 version of the Cloud SQL Proxy.

We highly recommend upgrading to v2 to take advantage of new features as v1 is mostly in maintenance mode (bug fixes and dep updates only).

You can check out the [migration guide](https://github.com/GoogleCloudPlatform/cloud-sql-proxy/blob/main/migration-guide.md) for more detailed steps to do so.

If there is anything holding you back from migrating, please let us know 😄

2024-08-06 19:04 UTC, jackwotherspoon commented
> hi @enocom could you update the examples or provide an example of how this would work with a poststart hook? I've been struggling to get it to work as described

Hi @mdering! 

Now that k8s supports sidecar configurations I would recommend taking a look at and using the Cloud SQL Proxy as an `initContainers` instead of a `postStart` hook:  Please see https://github.com/GoogleCloudPlatform/cloud-sql-proxy/issues/128#issuecomment-2264787327

2024-08-06 19:36 UTC, mdering commented
hi @jackwotherspoon, thanks for your help! I was interested in using it as a sidecar for jobs and services, is that no longer the pattern you recommend? It seems like the regular application won't start until the `initcontainers` all stop according to the docs, is there something im missing?

2024-08-09 07:23 UTC, devauxbr commented
Hi @mdering, the [new official "sidecar container" support in K8S](https://kubernetes.io/blog/2023/08/25/native-sidecar-containers/) is indeed a bit misleading, as it requires using `initContainer`but with an additionnal `restartPolicy: Always` to make it a sidecar 😅

2024-08-12 15:28 UTC, enocom commented
+1 to what @devauxbr said. @mdering if you're still getting stuck, feel free to open an issue and we can either document this better, or explore other options.